# Generated by Django 6.0 on 2026-03-16 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20260108_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='last_update',
            new_name='update_at',
        ),
    ]
