# Generated by Django 6.0 on 2026-03-16 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_last_update_product_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
